### PR TITLE
Linux x64 support

### PR DESCRIPTION
**Pull request by Dgzt**

### CODE REVIEW

**Comment by ThanosFisherman** [comment]
Hello,
Just wanted to report that I cloned your project, fetched linux natives and integrated it into my project. It seems to be working well on my linux machine.
I just get the following error which doesn't really affect the execution of the program
```
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : EGL: Failed to create window surface: An unrecognized attribute or attribute value was passed in the attribute list
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createGlfwWindow(Lwjgl3VulkanApplication.java:543)
		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:470)
		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:456)
		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.<init>(Lwjgl3VulkanApplication.java:170)
		io.github.thanosfisherman.dla.desktop.DesktopLauncher.main(DesktopLauncher.kt:33)
		io.github.thanosfisherman.dla.desktop.DesktopLauncher.main(DesktopLauncher.kt)
```

**Comment by Dgzt** [comment]
> Hello, Just wanted to report that I cloned your project, fetched linux natives and integrated it into my project. It seems to be working well on my linux machine.

Hi, thank you your report. Could you check what are the renderer and vendor? 

```java
System.out.println("OpenGL renderer: " + Gdx.gl.glGetString(GL20.GL_RENDERER));
System.out.println("OpenGL vendor: " + Gdx.gl.glGetString(GL20.GL_VENDOR));
```

These should print something similar texts like [these](https://github.com/google/angle/blob/572fd30ee23967ec6ba5b352b81146fc9fff6667/doc/ExtensionSupport.md#configuration-information). On my Linux I don't see these texts only Intel / Nvidia vendor, so I think the application passes the calls to the real OpenGL and doesn't pass to the angle's vulkan backend. Currently I don't know why.

> I just get the following error which doesn't really affect the execution of the program
> 
> ```
> [LWJGL] GLFW_PLATFORM_ERROR error
> 	Description : EGL: Failed to create window surface: An unrecognized attribute or attribute value was passed in the attribute list
> 	Stacktrace  :
> 		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
> 		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
> 		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createGlfwWindow(Lwjgl3VulkanApplication.java:543)
> 		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:470)
> 		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:456)
> 		com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.<init>(Lwjgl3VulkanApplication.java:170)
> 		io.github.thanosfisherman.dla.desktop.DesktopLauncher.main(DesktopLauncher.kt:33)
> 		io.github.thanosfisherman.dla.desktop.DesktopLauncher.main(DesktopLauncher.kt)
> ```

Yes, this is a known issue on nvidia gpu, [see](https://github.com/libgdx/libgdx/pull/7069). I've used this workaround in my implementation, so it works on Linux with nvidia gpu, just shows this message. Maybe a deeper investigation is needed.

**Comment by ThanosFisherman** [comment]
> These should print something similar texts like [these](https://github.com/google/angle/blob/572fd30ee23967ec6ba5b352b81146fc9fff6667/doc/ExtensionSupport.md#configuration-information). On my Linux I don't see these texts only Intel / Nvidia vendor, so I think the application passes the calls to the real OpenGL and doesn't pass to the angle's vulkan backend. Currently I don't know why.

I think you may be right. I'm currently using an arch based distro on a hybrid graphics laptop. When I run it with my Intel GPU I can see the following printout

```
OpenGL renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL vendor: Intel
```
Interestingly the stacktrace error I posted before doesn't pop up when running via intel. However when I switch to my Nvidia 1050ti I can see the error along with the following

```
OpenGL renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
```

**Comment by Dgzt** [comment]
LWJGL3 has debug mode and prints out what native files loaded.

```java
import org.lwjgl.system.Configuration;

Configuration.DEBUG.set(Boolean.TRUE);
```

And this is on Windows where the application can load angle with vulkan backend:

```
...
[LWJGL] Loading library: libEGL
        Module: org.lwjgl.egl
        libEGL.dll not found in org.lwjgl.librarypath=C:\Users\dgzt\AppData\Local\Temp\lwjgl_dgzt\3.3.3-snapshot\x64
        Loaded from system paths: C:\Users\dgzt\AppData\Local\Temp\libgdxdgzt\28cf07947d17892d76b91de4\libEGL.dll
[LWJGL] Loading JNI library: lwjgl_opengles
        Module: org.lwjgl.opengles
        Loaded from org.lwjgl.librarypath: C:\Users\dgzt\AppData\Local\Temp\lwjgl_dgzt\3.3.3-snapshot\x64\lwjgl_opengles.dll
[LWJGL] Loading library: libGLESv2
        Module: org.lwjgl.opengles
        libGLESv2.dll not found in org.lwjgl.librarypath=C:\Users\dgzt\AppData\Local\Temp\lwjgl_dgzt\3.3.3-snapshot\x64
        Loaded from system paths: C:\Users\dgzt\AppData\Local\Temp\libgdxdgzt\28cf07947d17892d76b91de4\libGLESv2.dll
[LWJGL] Loading JNI library: lwjgl_opengl
        Module: org.lwjgl.opengl
        Loaded from org.lwjgl.librarypath: C:\Users\dgzt\AppData\Local\Temp\lwjgl_dgzt\3.3.3-snapshot\x64\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
        Module: org.lwjgl.opengl
        opengl32.dll not found in org.lwjgl.librarypath=C:\Users\dgzt\AppData\Local\Temp\lwjgl_dgzt\3.3.3-snapshot\x64
        Loaded from system paths: C:\Windows\system32\OpenGL32.dll
OpenGL renderer: ANGLE (NVIDIA, Vulkan 1.3.280 (NVIDIA NVIDIA GeForce GTX 1050 Ti (0x00001C8C)), NVIDIA-561.9.0.0)
OpenGL vendor: Google Inc. (NVIDIA)
OpenGL version: OpenGL ES 3.2.0 (ANGLE 2.1.23894 git hash: b98e6bc07e88)
```
Can see it loads the boundled Google Angle's libs.

And this is on Linux:

```
...

[LWJGL] [ALC] ALC_SOFT_reopen_device was reported as available but an entry point is missing.
[LWJGL] Loading JNI library: lwjgl_opengles
	Module: org.lwjgl.opengles
	Extracting: file:/home/dgzt/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/d59211c8746d50cfb610bd38f8d817a94fbdf013/lwjgl-opengles-3.3.3-natives-linux.jar!/linux/x64/org/lwjgl/opengles/liblwjgl_opengles.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_dgzt/3.3.3+5/x64/liblwjgl_opengles.so
[LWJGL] Loading library: libGLESv2.so.2
	Module: org.lwjgl.opengles
	libGLESv2.so.2 not found in org.lwjgl.librarypath=/tmp/lwjgl_dgzt/3.3.3+5/x64
	Loaded from system paths: /usr/lib/libGLESv2.so.2
[LWJGL] Loading library: libEGL.so.1
	Module: org.lwjgl.egl
	libEGL.so.1 not found in org.lwjgl.librarypath=/tmp/lwjgl_dgzt/3.3.3+5/x64
	Loaded from system paths: /usr/lib/libEGL.so.1
[LWJGL] Loading JNI library: lwjgl_opengl
	Module: org.lwjgl.opengl
	Extracting: file:/home/dgzt/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/62c70a4b00ca5391882b0f4b787c1588d24f1c86/lwjgl-opengl-3.3.3-natives-linux.jar!/linux/x64/org/lwjgl/opengl/liblwjgl_opengl.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_dgzt/3.3.3+5/x64/liblwjgl_opengl.so
[LWJGL] Loading library: libGLX.so.0
	Module: org.lwjgl.opengl
	libGLX.so.0 not found in org.lwjgl.librarypath=/tmp/lwjgl_dgzt/3.3.3+5/x64
	Loaded from system paths: /usr/lib/libGLX.so.0
OpenGL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL vendor: Intel
OpenGL version: OpenGL ES 3.2 Mesa 24.2.3-arch1.1
```

Can see it loads the system's EGL and OpenGL libs instead of google angle's libs. This is why the ANGLE's text is not in the renderer and vendor text.

But can set custom path for these files in LWJGL3:

```java
import org.lwjgl.system.Configuration;

Configuration.OPENGLES_LIBRARY_NAME.set("/tmp/angle-linux-x64/dist/libGLESv2.so");
Configuration.EGL_LIBRARY_NAME.set("/tmp/angle-linux-x64/dist/libEGL.so");
```

But in this case the application crashes with the following exception:

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't initialize GLES
	at com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createGlfwWindow(Lwjgl3VulkanApplication.java:647)
	at com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:471)
	at com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createWindow(Lwjgl3VulkanApplication.java:457)
	at com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.<init>(Lwjgl3VulkanApplication.java:171)
	at com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.github.dgzt.gdx.lwjgl3.Lwjgl3VulkanApplication.createGlfwWindow(Lwjgl3VulkanApplication.java:643)
	... 4 more
Caused by: java.lang.IllegalStateException: There is no OpenGL ES context current in the current thread.
	at org.lwjgl.opengles.GLES.createCapabilities(GLES.java:294)
	at org.lwjgl.opengles.GLES.createCapabilities(GLES.java:240)
	... 9 more
```

**Comment by ThanosFisherman** [comment]
Yeah I get the exact same logs on my machine. The context thing is a threading issue. You could theoretically use `Gdx.app.postRunnable` (in core module) to workaround this issue but that won't solve the root cause of the problem. It seems that when you load the libs manually they get loaded either too early or too late. Could be a lwjgl issue. I tried various things but with no success so far. 😕 

Just a blind guess. Maybe try to load the natives using `System.loadLibrary` instead of `System.load()` or pack them in a jar and then load them. I have no idea though. 🤷‍♂️

**Comment by Dgzt** [comment]
I ran out the the ideas so I've [asked](https://discord.com/channels/677914184809185281/677914830027620352/1291663381375352874) it on the LWJGL's discord channel, maybe someone can help to us.

**Comment by Dgzt** [comment]
Seems this bug is also in the libGDX's angle implementation: https://github.com/libgdx/libgdx/issues/7473.

**Comment by ThanosFisherman** [comment]
After the insights from @Spasi I can now load the angle natives ok but I experience frequent freezes even with my discrete GPU. Maybe there's an issue with the implementation? I noticed that you load angle through reflection. Why is that? In addition I believe you don't need that `System.load` anymore.

**Comment by Dgzt** [comment]
> After the insights from @Spasi I can now load the angle natives ok but I experience frequent freezes even with my discrete GPU. Maybe there's an issue with the implementation? 

Good question. A deeper investigation is needed. 

> I noticed that you load angle through reflection. Why is that? In addition I believe you don't need that `System.load` anymore.

Do you mean [this line](https://github.com/Dgzt/gdx-lwjgl3-angle-vulkan/blob/3200d2d21ff6455dd6a784784862db1429c88da7/src/main/java/com/github/dgzt/gdx/lwjgl3/Lwjgl3VulkanApplication.java#L104)? This method is in the official libGDX repository also. The reason to use reflection because the angle class is in another library (gdx-lwjgl3 <-> gdx-lwjgl3-angle). In this repository can use non-reflection code but I think only the initialization will be a bit slowly and doesn't affect the runtime.

**Comment by ThanosFisherman** [comment]
Yeap exactly that line. I was surprised why you did it like that when you could simply do `AngleLoader.load()` but anyhow I think you don't even need this anymore. Why would you load Angle natives like [this](https://github.com/Dgzt/gdx-lwjgl3-angle-vulkan/blob/3200d2d21ff6455dd6a784784862db1429c88da7/src/main/java/com/github/dgzt/gdx/lwjgl3/angle/ANGLELoader.java#L203)? Even if you keep it, lwjgl still doesn't know about these natives anyway. I think you only need to use Spasi's methods directly from lwjgl to load the natives after you extract them thus revising [this](https://github.com/Dgzt/gdx-lwjgl3-angle-vulkan/blob/3200d2d21ff6455dd6a784784862db1429c88da7/src/main/java/com/github/dgzt/gdx/lwjgl3/Lwjgl3VulkanApplication.java#L145) part to something along the lines of

```java
  if (config.glEmulation == Lwjgl3ApplicationConfiguration.GLEmulation.ANGLE_GLES32) {
            Configuration.OPENGLES_LIBRARY_NAME.set("/path/ibGLESv2.so");
            Configuration.EGL_LIBRARY_NAME.set("/path/libEGL.so");
            GLFWNativeEGL.setEGLPath(EGL.getFunctionProvider());
            GLFWNativeEGL.setGLESPath(GLES.getFunctionProvider());
        }
        // rest of the code remains as-is
 ```
I don't want to confuse you though. If you have something else in mind go ahead. I will also play with this logic a bit longer and see where it leads.

**Comment by Dgzt** [comment]
> Yeap exactly that line. I was surprised why you did it like that when you could simply do `AngleLoader.load()` but anyhow I think you don't even need this anymore. Why would you load Angle natives like [this](https://github.com/Dgzt/gdx-lwjgl3-angle-vulkan/blob/3200d2d21ff6455dd6a784784862db1429c88da7/src/main/java/com/github/dgzt/gdx/lwjgl3/angle/ANGLELoader.java#L203)? Even if you keep it, lwjgl still doesn't know about these natives anyway. I think you only need to use Spasi's methods directly from lwjgl to load the natives after you extract them thus revising [this](https://github.com/Dgzt/gdx-lwjgl3-angle-vulkan/blob/3200d2d21ff6455dd6a784784862db1429c88da7/src/main/java/com/github/dgzt/gdx/lwjgl3/Lwjgl3VulkanApplication.java#L145) part to something along the lines of
> 
> ```java
>   if (config.glEmulation == Lwjgl3ApplicationConfiguration.GLEmulation.ANGLE_GLES32) {
>             Configuration.OPENGLES_LIBRARY_NAME.set("/path/ibGLESv2.so");
>             Configuration.EGL_LIBRARY_NAME.set("/path/libEGL.so");
>             GLFWNativeEGL.setEGLPath(EGL.getFunctionProvider());
>             GLFWNativeEGL.setGLESPath(GLES.getFunctionProvider());
>         }
>         // rest of the code remains as-is
> ```

My goal is keep the source code close to the original libGDX source code because I want to create PR into the libGDX repo if everything work well. But yeah, this is not a big change, so I rewrite to call `load` and the others method to `AngleLoader` directly. 

> I don't want to confuse you though. If you have something else in mind go ahead. I will also play with this logic a bit longer and see where it leads.

If you have any idea or suggestion this is welcome and just write here or create issue or discuss it on discord.

**Pull request merged**
